name: Publish

on:
  push:
    branches:
      - main
      - "renovate/*"

  pull_request:
    branches:
      - main

jobs:
  publish:
    name: Publish NPM Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensures full Git history is fetched

      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"

      - name: Ensure NPM Access
        run: npm whoami --registry https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_HANDLER }}

      - name: Configure Git User
        run: |
          git config --global user.name "@hellcat29a"
          git config --global user.email "bhiri22@gmail.com@users.noreply.github.com"

      - name: Install Dependencies
        run: npm install --f

      - name: Build Project
        run: npm run build

      - name: Create ~/.npmrc file
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PACKAGES_HANDLER }}" > ~/.npmrc

      - name: Publish Package from Dist Directory
        run: |
          cd dist/angular-file-uploader
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_HANDLER }}

      - name: Stage package-lock.json
        run: git add package-lock.json

      - name: Commit changes
        run: |
          git config --global user.email "bhiri22@gmail.com"
          git config --global user.name "@hellcat29a"
          git commit -m "fix: commit package-lock.json changes" || echo "No changes to commit"
