name: Publish

on:
  push:
    branches:
      - main
      - "renovate/*"

  pull_request:
    branches:
      - main

jobs:
  publish:
    name: Publish NPM Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"

      - name: Install Dependencies
        run: npm install --f

      - name: Build Project
        run: npx turbo run build --filter=@hellcat29a/angular-file-uploader

      - name: Debug Build Output
        run: |
          pwd
          find . -name "dist" -type d
          ls -R packages/angular-file-uploader/dist/file-uploader-popup

      - name: Publish Package
        run: |
          cd packages/angular-file-uploader/dist/file-uploader-popup
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_HANDLER }}
